Playlist_id:
  default: ''
  description:
    en: "playlist id"

Youtube_API_key:
  default: ''
  description:
    en: "Youtube API key"

Player_side:
  default: left
  type: enum
  choices:
    - left
    - right
  description:
    en: "Which side should the player appear on?"

Move_content:
  default: false
  description:
    en: "If checked, the player will push content aside when open."

Toggle_icon:
  default: "music"
  description:
    en: "Chose the icon for the player toggle"

Toggle_title:
  default: "Check out my music!"
  description:
    en: "The title text for the player toggle"

Now_playing_message:
  default: "Now playing"
  description:
    en: "The text for <b>Now Playing</b> message"

Disable_on_mobile:
  default: true
  description:
    en: "If checked, the player will be disabled on mobile devices"

extend_content_security_policy:
  type: list
  default: "script_src: https://cdnjs.cloudflare.com|script_src: https://www.youtube.com|script_src: https://s.ytimg.com|script_src: https://www.googleapis.com/youtube"
